### ISSUE TITLE
Recommendations from your Morning Session Team

### ISSUE THREAD

**Issue by D4nielJ** [elassis/mobile_version_portfolio#14]
## Hello Enmanuel,

We have some recommendations to make your project look better.

* You could try improving the indentation in your HTML, this way is more readable for others and you.
* With javascript you can fetch the form in a variable and use always the format form.nameOfInput to get the values of any input.
* Validation is not working properly from last excersice. I  would suggest you that you actually change it so that your emails are changed to lowercase before being sent to FormSpree
* There's a typo in line 92 of index.html

Nice job, your html looks really narrow!

**Comment by elassis** [comment]
correctly apply the recommendations
